Repository mojohaus/taglist-maven-plugin, pull requests merged in 2024-02, with the labels that each got.

#129 pom cleanup after parent update
  pom.xml
Labels: maintenance

#130 Add "FIXME" to default tags (in case of empty tags/tagOptions)
  src/main/java/org/codehaus/mojo/taglist/TagListReport.java
Labels: enhancement

#131 Require Maven 3.6.3+
  pom.xml
Labels: dependencies

#132 Upgrade plexus-utils to 4.0.0
  pom.xml
Labels: dependencies

#133 Apply spotless plugin
  pom.xml
  src/main/java/org/codehaus/mojo/taglist/FileAnalyser.java
  src/main/java/org/codehaus/mojo/taglist/ReportGenerator.java
  src/main/java/org/codehaus/mojo/taglist/TagListReport.java
  src/main/java/org/codehaus/mojo/taglist/beans/FileReport.java
  src/main/java/org/codehaus/mojo/taglist/beans/TagReport.java
  src/main/java/org/codehaus/mojo/taglist/tags/AbsTag.java
  src/main/java/org/codehaus/mojo/taglist/tags/GenericTag.java
  src/main/java/org/codehaus/mojo/taglist/tags/IgnoreCaseTag.java
  src/main/java/org/codehaus/mojo/taglist/tags/InvalidTagException.java
  src/main/java/org/codehaus/mojo/taglist/tags/RegExTag.java
  src/main/java/org/codehaus/mojo/taglist/tags/TagClass.java
  src/main/java/org/codehaus/mojo/taglist/tags/TagFactory.java
  src/test/java/org/codehaus/mojo/taglist/AbstractTaglistMojoTestCase.java
  src/test/java/org/codehaus/mojo/taglist/TaglistMojoBasicConfigTest.java
  src/test/java/org/codehaus/mojo/taglist/TaglistMojoCountingTagsTest.java
  src/test/java/org/codehaus/mojo/taglist/TaglistMojoLocalesTest.java
  src/test/java/org/codehaus/mojo/taglist/TaglistMojoTagClassesTest.java
  src/test/java/org/codehaus/mojo/taglist/TaglistMojoTagsTest.java
  src/test/java/org/codehaus/mojo/taglist/beans/FileReportTestCase.java
  src/test/java/org/codehaus/mojo/taglist/stubs/BasicConfigProjectStub.java
  src/test/java/org/codehaus/mojo/taglist/stubs/CountingTagsProjectStub.java
  src/test/java/org/codehaus/mojo/taglist/stubs/LocaleProjectStub.java
  src/test/java/org/codehaus/mojo/taglist/stubs/TagClassesProjectStub.java
  src/test/java/org/codehaus/mojo/taglist/stubs/TagsProjectStub.java
Labels: maintenance

#134 Code cleanups
  src/main/java/org/codehaus/mojo/taglist/FileAnalyser.java
  src/main/java/org/codehaus/mojo/taglist/TagListReport.java
  src/main/java/org/codehaus/mojo/taglist/beans/FileReport.java
  src/main/java/org/codehaus/mojo/taglist/beans/TagReport.java
  src/main/java/org/codehaus/mojo/taglist/tags/AbsTag.java
  src/main/java/org/codehaus/mojo/taglist/tags/GenericTag.java
  src/main/java/org/codehaus/mojo/taglist/tags/IgnoreCaseTag.java
  src/main/java/org/codehaus/mojo/taglist/tags/RegExTag.java
  src/main/java/org/codehaus/mojo/taglist/tags/TagClass.java
  src/test/java/org/codehaus/mojo/taglist/TaglistMojoBasicConfigTest.java
  src/test/java/org/codehaus/mojo/taglist/TaglistMojoCountingTagsTest.java
  src/test/java/org/codehaus/mojo/taglist/TaglistMojoLocalesTest.java
  src/test/java/org/codehaus/mojo/taglist/TaglistMojoTagClassesTest.java
  src/test/java/org/codehaus/mojo/taglist/TaglistMojoTagsTest.java
  src/test/java/org/codehaus/mojo/taglist/stubs/BasicConfigProjectStub.java
  src/test/java/org/codehaus/mojo/taglist/stubs/CountingTagsProjectStub.java
  src/test/java/org/codehaus/mojo/taglist/stubs/LocaleProjectStub.java
  src/test/java/org/codehaus/mojo/taglist/stubs/TagClassesProjectStub.java
  src/test/java/org/codehaus/mojo/taglist/stubs/TagsProjectStub.java
Labels: java, maintenance

#66 [#64] Allow empty displayName tags in TagClass.
  src/main/java/org/codehaus/mojo/taglist/beans/TagReport.java
Labels: feature

#135 Bump maven-reporting-impl to 3.1.0
  pom.xml
Labels: dependencies

#136 Bump maven-wrapper to 3.2.0 and Maven to 3.9.6
  .mvn/wrapper/maven-wrapper.properties
  mvnw
  mvnw.cmd
Labels: maintenance
